name: Nuclei

on: push

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: 'https://juice-shop.herokuapp.com/'
